version: "3.4"

services:
  dappnode_installer:
    build: .
    privileged: true
    environment:
      - BUILD=false # In case you want to re-generate a all the images, not recommended
      - CLEAN=true # it remove the images directory
      - UNATTENDED=${UNATTENDED} # UNATTENDED version
      - BASE_OS=${BASE_OS} # Base OS version (debian or ubuntu)
    volumes:
      - ./images:/images
      - "/var/run/docker.sock:/var/run/docker.sock"
